[project]
name = 'Blockchain-Based-Employee-Credential-Verification'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.certification-tracking]
path = 'contracts/certification-tracking.clar'
clarity_version = 2
epoch = 2.5

[contracts.education-verification]
path = 'contracts/education-verification.clar'
clarity_version = 2
epoch = 2.5

[contracts.employment-history]
path = 'contracts/employment-history.clar'
clarity_version = 2
epoch = 2.5

[contracts.identity-verification]
path = 'contracts/identity-verification.clar'
clarity_version = 2
epoch = 2.5
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
